### ISSUE TITLE
AMD ShadowFX sample is hangs on Intel HD 4000 GPU

### ISSUE THREAD

**Issue by Andreyogld3d** [GPUOpen-Effects/ShadowFX#4]
Hi Jason Stewart!
I have problem on Intel HD 4000, the shadowFx sample is hangs.

Also i created the topic in the amd developping forum:
https://community.amd.com/thread/196125

**Comment by jstewart-amd** [comment]
We do not currently test ShadowFX (nor other GPUOpen-Effects libraries and samples) on integrated graphics or APUs. This may change in the future, but for now, only discrete GPUs are officially supported. I have updated the readme to clarify this.

However, @akharlamov-amd has graciously volunteered to test on his HD 4000, in case it is an easy fix. I'll keep the issue open and assign it to him. No guarantees, though. If the fix is a big change, we may have to fall back on "only discrete GPUs are officially supported."

**Comment by jstewart-amd** [comment]
Also, do you have latest and greatest from the repo? I ask because a crash fix for non-AMD hardware was pushed yesterday.

**Comment by Andreyogld3d** [comment]
Hi Jason Stewart, thanks for your response!

> do you have latest and greatest from the repo? 

No, i have downloaded the ShadowFX from the date 28.12.2016.
But, I will try the latest update(from 29.12.2016) or later) of the ShadowFX and let you now if the crash is still exist.
Also, the ShadowFX is working fine on nVidia 210! (D3D_FEATURE_LEVEL_10_1)

**Comment by Andreyogld3d** [comment]
Hi Jason Stewart, today I tried the new version of ShadowFX, AGS library was updated:

#define AMD_AGS_LIB_VERSION_MAJOR 3
#define AMD_AGS_LIB_VERSION_MINOR 1
#define AMD_AGS_LIB_VERSION_PATCH 1

but, the issue is stll exist.

**Comment by Andreyogld3d** [comment]
Hi!
On latest driver for Intel HD 4000 (Driver Date 12.21.2015, Version 10.18.10.4358) the issue is absent.

But during debugging, the sample is working slowly.
